#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#The redirection must be a “301 Moved Permanently”

STRING="Hello World!"

sudo  apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "$STRING" | sudo tee /var/www/html/index.nginx-debian.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/relars91 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default


sudo service nginx restart

