#!/usr/bin/env bash
#Configure your Nginx server so that i will have a custom error page

STRING="Hello World!"

sudo  apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "$STRING" | sudo tee /var/www/html/index.nginx-debian.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/relars91 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#creating a custom 404 page

echo "Ceci n'est pas une page" | sudo tee  /var/www/html/404.html

new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

#restart nginx 
sudo service nginx restart

